import { EventEmitter, OnInit, ChangeDetectorRef, OnDestroy } from '@angular/core';
import { SortType, SelectionType } from '../../types';
import { DataTableColumnDirective } from '../columns';
import { Subject } from "rxjs/Subject";
import { BehaviorSubject, Observable } from "../../../node_modules/rxjs";
import 'rxjs/add/observable/of';
import 'rxjs/add/observable/combineLatest';
import 'rxjs/add/operator/takeUntil';
import 'rxjs/add/operator/startWith';
export declare class DataTableHeaderComponent implements OnInit, OnDestroy {
    private cd;
    ngOnInit(): void;
    ngOnDestroy(): void;
    constructor(cd: ChangeDetectorRef);
    sortAscendingIcon: any;
    sortDescendingIcon: any;
    scrollbarH: boolean;
    dealsWithGroup: boolean;
    stickyHeader: boolean;
    columnsResize: Subject<any>;
    _columnsResize: Subject<any>;
    private destroy$;
    columns$: BehaviorSubject<any[]>;
    headerColumns$: Observable<any[]>;
    _innerWidth: number;
    innerWidth: number;
    sorts: any[];
    sortType: SortType;
    allRowsSelected: boolean;
    selectionType: SelectionType;
    reorderable: boolean;
    dragEventTarget: any;
    headerHeight: any;
    columns: any[];
    offsetX: number;
    sort: EventEmitter<any>;
    reorder: EventEmitter<any>;
    resize: EventEmitter<any>;
    select: EventEmitter<any>;
    columnContextmenu: EventEmitter<{
        event: MouseEvent;
        column: any;
    }>;
    _columnsByPin: any;
    _columnGroupWidths: any;
    _offsetX: number;
    _columns: any[];
    _headerHeight: string;
    _styleByGroup: {
        left: {};
        center: {};
        right: {};
    };
    onLongPressStart({event, model}: {
        event: any;
        model: any;
    }): void;
    onLongPressEnd({event, model}: {
        event: any;
        model: any;
    }): void;
    readonly headerWidth: string;
    trackByGroups(index: number, colGroup: any): any;
    columnTrackingFn(index: number, column: any): any;
    onColumnResized(width: number, column: DataTableColumnDirective): void;
    onColumnReordered({prevIndex, newIndex, model}: any): void;
    onSort({column, prevValue, newValue}: any): void;
    calcNewSorts(column: any, prevValue: number, newValue: number): any[];
    setStylesByGroup(): void;
    calcStylesByGroup(group: string): any;
}
